[build]
  command = "npm install --prefix server && npm install --prefix client && npm run build --prefix client"
  publish = "client/dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true